### ISSUE TITLE
试试这个（

### ISSUE THREAD

**Issue by LoveLoliii** [simon300000/bilibili-live-danmaku-api#2]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `bilibili-live-danmaku-api@1.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/bilibili-live-danmaku-api/index.d.ts b/node_modules/bilibili-live-danmaku-api/index.d.ts
new file mode 100644
index 0000000..7840713
--- /dev/null
+++ b/node_modules/bilibili-live-danmaku-api/index.d.ts
@@ -0,0 +1 @@
+declare module 'bilibili-live-danmaku-api';
\ No newline at end of file
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by simon300000** [comment]
哇哦 不过这也不算是我这边的问题ba
发布出去的应该是纯js

**Comment by LoveLoliii** [comment]
> 哇哦 不过这也不算是我这边的问题ba 发布出去的应该是纯js

哎嘿 我也不懂，ts引入要这个定义

**Comment by simon300000** [comment]
唔 这有点怪 唔

**Comment by LoveLoliii** [comment]
> 唔 这有点怪 唔

就是 import的时候会提示这个:
```
无法找到模块“bilibili-live-danmaku-api”的声明文件。“R:/git_project/catcat-dm-react/node_modules/bilibili-live-danmaku-api/index.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/bilibili-live-danmaku-api` (如果存在)，或者添加一个包含 `declare module 'bilibili-live-danmaku-api';` 的新声明(.d.ts)文件
```

**Comment by LoveLoliii** [comment]
> 唔 这有点怪 唔

用require也是没问题的（就是提示框自己亮了
```
可将“要求”调用转换为导入。
```
